### ISSUE TITLE
missing restiming data in statsd

### ISSUE THREAD

**Issue by softwareklinic** [springernature/boomcatch#68]
I understand this is not a boomerang issue --- but still wanted to post here to see if any help can be made available.
We are using boomcatch -- to capture the beacon data and then forward to statsd... we are seeing the navtiming and rt data in statsd but not the restiming....

**Comment by softwareklinic** [comment]
I just received update from the boomerang github repo that boomcatch is not decompressing the compressed resourcetiming and is not compatible... is this correct... and if yes when can we implement/fix it

**Comment by bluesmoon** [comment]
This is a dup of #49

**Comment by joseluisbolos** [comment]
Hi @softwareklinic - As @bluesmoon mentioned, this looks like a duplicate of #49.

I will try to get this issue fixed for the next major release. I will be closing this issue now, you can follow the progress in #49.

Thanks!
