### ISSUE TITLE
Inconsistent data from Boomerang to Boomcatch

### ISSUE THREAD

**Issue by marcelinhov2** [springernature/boomcatch#74]
I'd added 2 console.log at the send event ( see Logs [here](https://gist.github.com/marcelinhov2/c4c89d0d1bf8a17c7828a2927ec56771) ):

![image](https://cloud.githubusercontent.com/assets/232648/19701995/89565e1c-9adc-11e6-9543-7369dcbc44ba.png)

As you can see, at the first log ( before data "turns" into mappedData ) there are infos about restiming, mem, dom, cpu and etc... but at the second log, I just have infos about rt and navtiming.

Am I missing something?

Thanks.

**Comment by hollsk** [comment]
Hi @marcelinhov2 - I'm really sorry about the lengthy delay in getting back to you about this. It looks like you're using the default mapper `statsd`, which normalises the data as it comes through (and removes a lot of fields!). We'd intended to remove normalisation entirely as explained in #55 but it seems that we didn't ever get round to it. Thank you for the reminder! :D 

In the meantime, you can skip the normalisation process by passing the `--mapping unmapped` parameter when you run Boomcatch. 

Hope that helps, and sorry (again) for the wait.
