### ISSUE TITLE
Getting Error while installing Boomcatch 

### ISSUE THREAD

**Issue by hjain4** [springernature/boomcatch#75]
Hi, I am installing boomcatch on ubuntu 14.0.1 version but each time i am trying getting error attached in screenshot can you please help @pixeltrix @baob 
![dest](https://cloud.githubusercontent.com/assets/13941641/19832073/2dd58962-9e2b-11e6-9fab-dae69e28ee68.PNG)

**Comment by pixeltrix** [comment]
@hjain4 not sure why you tagged me as I have nothing to do with this project but looking at the error `Error: not found: make` that would suggest that you don't have `build-essential` installed via `apt-get`. Try doing `sudo apt-get install build-essential` and then re-installing. If it's not that then for some reason `make` isn't in your `PATH` - why not, I don't know and is probably something to do with how you have your machine configured.

**Comment by joseluisbolos** [comment]
Closing issue - user is missing `make`.
